### ISSUE TITLE
群公告被显示为js数据，且内容不全

### ISSUE THREAD

**Issue by 1ndeed** [ehForwarderBot/efb-qq-plugin-go-cqhttp#12]
群消息中发布公告后，telegram接收到的是这样的形式：

{"app":"com.tencent.mannounce","config":{"ctime":1632017790,"forward":0,"token":"3d56417a2160c9f7cc4f3f09acdc44ff"},"desc":"群公告","extra":{"app_type":1,"appid":1101236949,"uin":1113447723},"meta":{"mannounce":{"cr":1,"encode":1,"fid":"4c02de36000000007e9d466181a70200","gc":"920519244","sign":"f0cc3e61506926cdd26900abd39a4f73","text":"6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGv6L+Z5piv5Y6f5p2l55qE5raI5oGvCg==","title":"576k5YWs5ZGK","tw":1,"uin":"1113447723"}},"prompt":"[群公告]这是原来的消息这是原来的消息这是原来的消息这是原来的消息这是原来的消息这是原来的消息这是原来的消 息这是原来的消息这是原来的消息这是原…","ver":"1.0.0.43","view":"main"}

这不是log，这就是telegram最终收到的信息。  
而且可以看到text中是base64的加密信息，解密后可以得到完整的群公告。
但后面的prompt信息只显示了一定长度的信息，后面的信息被省略为...了。

希望能添加功能把com.tencent.mannounce应用转换为普通的text且保留完整信息。

**Comment by Ashinch** [comment]
#13

貌似现在卡片消息都是JSON类型的了，测试拿到了一些app键的值。
