### ISSUE TITLE
[feature request]支持语音消息的接收

### ISSUE THREAD

**Issue by ckn4** [ehForwarderBot/efb-qq-plugin-go-cqhttp#15]
go-cqhttp原项目已支持，但是efb插件目前无法接收语音消息，会提示“不支持的消息类型，请在客户端查看”。
接收到的语音消息可能需要解码。[#440](https://github.com/Mrs4s/go-cqhttp/issues/440)

**Comment by XYenon** [comment]
Supported by https://github.com/ehForwarderBot/efb-qq-plugin-go-cqhttp/pull/23
