### ISSUE TITLE
无法接收文件

### ISSUE THREAD

**Issue by iaurman** [ehForwarderBot/efb-qq-plugin-go-cqhttp#40]
```
/home/riley/.local/lib/python3.10/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py:369: RuntimeWarning: coroutine 'GoCQHttp.async_download_file' was never awaited
  self.async_download_file(**param_dict)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

从cqhttp到slave到plugin都是最新版

**Comment by lq-259** [comment]
我还以为是我代理的问题排查了半天

**Comment by phoenixxie0** [comment]
同样无法接收文件，但报错方式不一样，建议你更换python3.8版本重新安装一次。
`<Message, <SystemChatMember: System (__system__) @ <SystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>>@<SystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)> [Text]: 小号小号(.) uploaded a file to you
Filename: 33.txt
File size: 545; __offline_file__.1658815595>
2022-07-26 14:06:35,287 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.update_chat_obj; chat_object_cache.py:146)
    Trying to update key ('milkice.qq', '__offline_file__') with object <SystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>. Full update: False
2022-07-26 14:06:35,287 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.update_chat_obj; chat_object_cache.py:148)
    Key ('milkice.qq', '__offline_file__') is not in cache. Do compound enrol.
2022-07-26 14:06:35,288 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.compound_enrol; chat_object_cache.py:53)
    Compound enrol 2 members of <ETMSystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>
2022-07-26 14:06:35,288 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.enrol; chat_object_cache.py:65)
    Enrolling key ('milkice.qq', '__offline_file__') with value <ETMSystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>
2022-07-26 14:06:35,290 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3185)
    ('SELECT "t1"."slave_uid", "t1"."master_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."slave_uid" = ?)', ['milkice.qq __offline_file__'])
2022-07-26 14:06:35,291 [DEBUG]: efb_telegram_master.slave_message (slave_message.get_slave_msg_dest; slave_message.py:245)
    [__offline_file__.1658815595] The message should deliver to None
2022-07-26 14:06:35,291 [DEBUG]: efb_telegram_master.slave_message (slave_message.get_slave_msg_dest; slave_message.py:253)
    [__offline_file__.1658815595] Message is in chat <ETMSystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>
2022-07-26 14:06:35,291 [DEBUG]: efb_telegram_master.slave_message (slave_message.get_slave_msg_dest; slave_message.py:264)
    [__offline_file__.1658815595] Message is sent to Telegram chat 93189374, with header "🐧💻 ℹ Offline File Upload Event, System:".
2022-07-26 14:06:35,292 [DEBUG]: efb_telegram_master.slave_message (slave_message.slave_message_text; slave_message.py:318)
    [__offline_file__.1658815595] Sending as a text message.`

**Comment by iaurman** [comment]
> 同样无法接收文件，但报错方式不一样，建议你更换python3.8版本重新安装一次。
> `<Message, <SystemChatMember: System (__system__) @ <SystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>>@<SystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)> [Text]: 小号小号(.) uploaded a file to you Filename: 33.txt File size: 545; __offline_file__.1658815595>`
> ` 2022-07-26 14:06:35,287 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.update_chat_obj; chat_object_cache.py:146)`
> ` Trying to update key ('milkice.qq', '__offline_file__') with object <SystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>. Full update: False`
> `2022-07-26 14:06:35,287 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.update_chat_obj; chat_object_cache.py:148)`
> ` Key ('milkice.qq', '__offline_file__') is not in cache. Do compound enrol.`
> `2022-07-26 14:06:35,288 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.compound_enrol; chat_object_cache.py:53)`
> ` Compound enrol 2 members of <ETMSystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>`
> `2022-07-26 14:06:35,288 [DEBUG]: efb_telegram_master.chat_object_cache (chat_object_cache.enrol; chat_object_cache.py:65)`
> ` Enrolling key ('milkice.qq', '__offline_file__') with value <ETMSystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>`
> `2022-07-26 14:06:35,290 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3185)`
> ` ('SELECT "t1"."slave_uid", "t1"."master_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."slave_uid" = ?)', ['milkice.qq __offline_file__'])`
> `2022-07-26 14:06:35,291 [DEBUG]: efb_telegram_master.slave_message (slave_message.get_slave_msg_dest; slave_message.py:245)`
> ` [__offline_file__.1658815595] The message should deliver to None`
> `2022-07-26 14:06:35,291 [DEBUG]: efb_telegram_master.slave_message (slave_message.get_slave_msg_dest; slave_message.py:253)`
> ` [__offline_file__.1658815595] Message is in chat <ETMSystemChat: ℹ Offline File Upload Event (__offline_file__) @ 🐧QQ Slave (milkice.qq)>`
> `2022-07-26 14:06:35,291 [DEBUG]: efb_telegram_master.slave_message (slave_message.get_slave_msg_dest; slave_message.py:264)`
> ` [__offline_file__.1658815595] Message is sent to Telegram chat 93189374, with header "🐧💻 ℹ Offline File Upload Event, System:".`
> `2022-07-26 14:06:35,292 [DEBUG]: efb_telegram_master.slave_message (slave_message.slave_message_text; slave_message.py:318)`
> ` [__offline_file__.1658815595] Sending as a text message.`

。。。
还是async敢死队的问题，目前解决办法可以是回退旧版本：

```
git clone https://github.com/ehForwarderBot/efb-qq-plugin-go-cqhttp.git
cd efb-qq-plugin-go-cqhttp
git checkout d1e79d8
cp -f ./efb_qq_plugin_go_cqhttp/* ~/.local/lib/python3.10/site-packages/efb_qq_plugin_go_cqhttp/
```

**Comment by phoenixxie0** [comment]
你是怎么解决pillow版本问题的？我是直接clone之后。删了版本依赖再装

**Comment by iaurman** [comment]
> 你是怎么解决pillow版本问题的？我是直接clone之后。删了版本依赖再装

我就是9.0.1的Pillow，没有遇到pillow相关的报错

话说github上的efb-telegram-master没有要求Pillow版本呀

**Comment by phoenixxie0** [comment]
会报错
EFBException(self._("WebP support of Pillow is required.\n"
ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.
Please refer to Pillow Documentation for instructions.

**Comment by iaurman** [comment]
> 会报错
> EFBException(self._("WebP support of Pillow is required.\n"
> ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.
> Please refer to Pillow Documentation for instructions.

没遇到过

**Comment by phoenixxie0** [comment]
2022-07-28 12:33:42,408 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3185)
    ('INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_member_uid", "media_type", "mime", "file_id", "file_unique_id", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['93189374.62', None, '__offline_file__.1658982820', '小号小号(.) uploaded a file to you\nFilename: DSC07323.xmp\nFile size: 8751', 'milkice.qq __offline_file__', 'milkice.qq __system__ __offline_file__', 'Text', None, None, None, 'Text', 'blueset.telegram', datetime.datetime(2022, 7, 28, 12, 33, 42, 406179)])
2022-07-28 12:33:42,451 [DEBUG]: efb_telegram_master.db (db.add_or_update_message_log; db.py:420)
    [93189374.62] Database insert/update outcome: 1
2022-07-28 12:33:42,455 [DEBUG]: urllib3.connectionpool (connectionpool._new_conn; connectionpool.py:228)
    Starting new HTTP connection (1): 14.22.6.247:80
2022-07-28 12:33:42,502 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:456)
    http://14.22.6.247:80 "GET /ftn_handler/ebce6c4164c601659ae029a5c4141e2bd18e9ac45a53f669ee82f5e62547973f2a60d859cd33de0d03882c3597bd678e72997a9070976e573affb08384b679ee HTTP/1.1" 200 8751
2022-07-28 12:33:42,559 [ERROR]: asyncio (base_events.default_exception_handler; base_events.py:1707)
    Task exception was never retrieved
future: <Task finished name='Task-55' coro=<GoCQHttp.__init__.<locals>.handle_offline_file_upload_msg.<locals>._handle_offline_file_upload_msg() done, defined at /usr/local/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py:356> exception=RuntimeError('asyncio.run() cannot be called from a running event loop')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 369, in _handle_offline_file_upload_msg
    await self.async_download_file(**param_dict)
  File "/usr/local/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 1058, in async_download_file
    efb_msg.chat = asyncio.run(self.chat_manager.build_efb_chat_as_private(context))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
/usr/local/lib/python3.8/asyncio/base_events.py:1844: RuntimeWarning: coroutine 'ChatManager.build_efb_chat_as_private' was never awaited
  handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-07-28 12:33:45,071 [INFO]: quart.app (__init__._handle_event; __init__.py:596)
    received event: meta_event.heartbeat
[2022-07-28 12:33:45,071] INFO in __init__: received event: meta_event.heartbeat
2022-07-28 12:33:45,146 [DEBUG]: telegram.bot (bot.get_updates; bot.py:3068)
    No new updates found.

依旧不能接收文件
