### ISSUE TITLE
安装过程中出现Failed to build Pillow

### ISSUE THREAD

**Issue by phoenixxie0** [ehForwarderBot/efb-qq-plugin-go-cqhttp#41]
使用pip install git+https://github.com/XYenon/efb-qq-plugin-go-cqhttp安装，过程中出现Failed to build Pillow
`
Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [175 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-3.8/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-3.8/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-f8dxj38r/pillow_b8a5444cd30748ae8a41d2096105e73d/setup.py", line 989, in <module>
          setup(
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-f8dxj38r/pillow_b8a5444cd30748ae8a41d2096105e73d/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-f8dxj38r/pillow_b8a5444cd30748ae8a41d2096105e73d/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
`

**Comment by phoenixxie0** [comment]
根据日志，似乎是需要安装jpeg-dev包才能编译？

**Comment by phoenixxie0** [comment]
efb-qq-plugin-go-cqhttp需要的依赖是Pillow~=9.0.1，而efb_telegram_master需要的是9.2，不然会报错raise EFBException(self._("WebP support of Pillow is required.\n"
ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.
Please refer to Pillow Documentation for instructions.
无法启动

**Comment by XYenon** [comment]
efb_telegram_master 好像并没有要求 Pillow 版本 https://github.com/ehForwarderBot/efb-telegram-master/blob/0850aeb294260c3cc14d382991837f99e12fae8c/setup.py#L57

编译失败请按照报错给出的 Pillow 官方文档操作

**Comment by phoenixxie0** [comment]
efb_telegram_master确实没有在安装过程中设定版本要求，但是在运行过程中会检测pillow的版本是否支持WebP，如果不支持，就会出现一些问题。另外编译的问题已经找到了，是少了jpeg-dev。

**Comment by phoenixxie0** [comment]
直接将依赖的Pillow~=9.0.1修改为Pillow>=9.0.1应该是好方案，目前我是这样做的，没有发现引入什么问题

**Comment by xiexiaopeng2002** [comment]
> 直接将依赖的Pillow~=9.0.1修改为Pillow>=9.0.1应该是好方案，目前我是这样做的，没有发现引入什么问题

我在使用python3.11的环境，已经不支持Pillow<9.3了
![image](https://github.com/ehForwarderBot/efb-qq-plugin-go-cqhttp/assets/77517276/c807eca2-ad18-4f5c-9ba9-8f298e1dfbf7)
